server:
  port: 8089


spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/sardor
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://${EUREKA_HOST:localhost}:8761/eureka/}
  instance:
    preferIpAddress: true




jwt:
  secret: vn54uignvurigh8gt9vetrghnu5gieuirgnerj5i5
  accessTokenExpiration: 3500000
  refreshTokenExpiration: 85500000

springdoc:
  swagger-ui:
    config-url: /api/auth/v3/api-docs/swagger-config
    url: /api/auth/swagger-ui
    path: /api/auth/swagger-ui